### ISSUE TITLE
Defined but Unused Functions in Launch.h/cpp

### ISSUE THREAD

**Issue by uicm-mas** [JFounderSDR/openSCA#2]
I found that across the whole project, the following functions are ONLY declared and defined in Launch.h but never called elsewhere. What are their functions? The comments are not easy to understand.
+ getFileRef
+ getTaskParamsFromSPD
+ getExecParamsFromPRF
+ changeExecParamsFormat
+ changeParamsFormat
+ killProcess
+ loadFile
+ spawnProcess
+ isFileExists

Also, may I know what the var m_fsRoot and m_sdrRoot stand for?

Thx

**Comment by JFounderSDR** [comment]
Hi:
The functions listed are defined and called in LaunchNode.cpp file. Generally, functions are declared in .h file, and defined in .cpp file.

**Comment by uicm-mas** [comment]
Yes, i am aware that all of them are realized and called in LaunchNode.cpp. But these functions were never USED elsewhere.
