### ISSUE TITLE
Mismatched return var type in \launchNode.cpp

### ISSUE THREAD

**Issue by uicm-mas** [JFounderSDR/openSCA#3]
line 78 and 87 in \frameworks\BootLoader\src\launchNode.cpp
Why does the function returns a CF::File_ptr type rather than the CF::File_var, as defined by the getfileref function?

**Comment by JFounderSDR** [comment]
From the point of CORBA programming, both _ptr type and _var type can be returned. But if returns _var type, then the object reference count will increase by one. When reference count value decreases to 0, the object reference will be unavailable. If returns a _ptr type, the object reference counts won't increase. It depends on your requirement. Generally,  we return a _ptr type, and use a _var type to receive function return value.

**Comment by uicm-mas** [comment]
Yes, I got it, thank you very much!
